### ISSUE TITLE
Cannot place LIMIT order, getting error "TE_PRICE_TOO_SMALL"

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [phemex/phemex-python-api#3]
I'm following the [documentation ](https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#placeorderwithput) here, trying to place a LIMIT order like this.
`client.place_order({"symbol":"DOGEUSD","clOrdID":"cryptomarauder1","side":Client.SIDE_BUY,"orderQty":10000,"ordType":Client.ORDER_TYPE_LIMIT,"priceEp":0.2250,"takeProfitEp":0.2500,"stopLossEp":0.2200})`

But I'm getting this error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev\tradingview-webhook\phemex_python_api\phemex\client.py", line 91, in place_order
    return self._send_request("post", "/orders", body=params)
  File "C:\dev\tradingview-webhook\phemex_python_api\phemex\client.py", line 76, in _send_request
    raise PhemexAPIException(response)
phemex_python_api.phemex.exceptions.PhemexAPIException: HTTP(code=200), API(errorcode=11055): TE_PRICE_TOO_SMALL
```

I don't think the price is too small because my orderQty is 10000 which is a big amount. I tried with different amounts but nothing worked out. I'm always getting the same error.

**Comment by lirwin3007** [comment]
For anyone with this issue, the likely cause is given by the following line from the docs:
 > Fields with post-fix "Ep" are scaled prices, priceScale in [products](https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#queryproductinfo)

This means the "priceEp" field should be multiplied by some number (normally ~1000).
As a result, the API is interpreting `"priceEp":0.2250` as a request to buy for a price something like 0.000225 - which is too small, triggering the `TE_PRICE_TOO_SMALL` error

This will be an issue for the `takeProfitEp` and `stopLossEp` fields as well
